name: Log AIPS Signature

on:
  push:
    paths:
      - "README.md"

jobs:
  generate-signature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate SHA256 Signature
        run: |
          HASH=$(sha256sum README.md | awk '{ print $1 }')
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          mkdir -p log

          if [ ! -f log/signature-history.json ]; then
            echo "[]" > log/signature-history.json
          fi

          jq --arg hash "$HASH" --arg time "$TIMESTAMP" \
          '. += [{"timestamp": $time, "sha256": $hash}]' \
          log/signature-history.json > tmp.json && mv tmp.json log/signature-history.json

      - name: Commit Signature Log
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔒 Update AIPS signature log"
          file_pattern: log/signature-history.json
